### PR TITLE
[BACKLOG-37110]-TAB functionality on Menubar.

### PR DESCRIPTION
**Pull request by phalguni-a**
@pentaho/wcag , Please review

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 48s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — CHANGES_REQUESTED** [review]
@phalguni-a wasn't this the bug for which I had proposed the fix: https://github.com/dcleao/pentaho-commons-gwt-modules/tree/fix-main-menu-tab? If so, why do you prefer this solution?

**Comment by phalguni-a** [comment]
> @phalguni-a wasn't this the bug for which I had proposed the fix: [dcleao/pentaho-commons-gwt-modules@bb07330](https://github.com/dcleao/pentaho-commons-gwt-modules/commit/bb07330fa4eb1cca52bd6efa443972fdd8dddaec)? If so, why do you prefer this solution?

@dcleao I didn't realize you were referring to this bug. Can you please create a PR for those commits in that case?

**Comment by dcleao** [comment]
@phalguni-a I will not be working on this story (any time soon, afaik).
The fix I provided, you can see it now as part of my code review.
My proposal is to fix the utilities, and not the places calling it.
GWT's `FocusImpl.getFocusImplForPanel()` already handles the asynchronicity for browsers that need it.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **7**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-217/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by dcleao — APPROVED** [review]

**Review by soagarwal1 — APPROVED** [review]

**Pull request merged**
