### PR TITLE
Merging wcag into master

### PR DESCRIPTION
**Pull request by AAravind27**

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 9m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **232**, Failures: **0**, Skipped: **175** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-264/1/testReport)

 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Review by phalguni-a — APPROVED** [review]

**Review by phalguni-a — COMMENTED** [review]
Build seems to be getting failed. This needs to be merged only after the build is fixed.

**Review by phalguni-a — CHANGES_REQUESTED** [review]
Build seems to be getting failed. This needs to be merged only after the build is fixed.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 4m 50s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
:ok_hand: All tests passed!
 
Tests run: **371**, Failures: **0**, Skipped: **295** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-264/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by phalguni-a** [comment]
Build is successful now. Will go ahead with the merge..

**Review by phalguni-a — APPROVED** [review]

**Pull request merged**
