### PR TITLE
[BACKLOG-36851] : Focus Visible - Accessibility -  PUC Home Page –Dat…

### PR DESCRIPTION
**Pull request by addagudi**
…a Source Wizard (SQL Query)

### CODE REVIEW

**Comment by addagudi** [comment]
@pentaho/wcag Please review

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-233/1/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by hv-vamsi — APPROVED** [review]

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 35s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-233/2/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
Duplicate of https://github.com/pentaho/pentaho-commons-xul/pull/228 ?

**Comment by addagudi** [comment]
Waiting for the QA signoff for this change in wcag branch.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 1m 36s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
:ok_hand: All tests passed!
 
Tests run: **18**, Failures: **0**, Skipped: **0** &nbsp;&nbsp; [Test Results](https://wingman.orl.eng.hitachivantara.com/job/projects/job/xul/job/PR-233/3/testReport)

 ---
 
 

:information_source:  _This is an automatic message_

**Review by rmansoor — APPROVED** [review]

**Pull request merged**
