### PR TITLE
[BACKLOG-37966] Toolbar improvements for PIR+PDD

### PR DESCRIPTION
**Pull request by AAravind27**
@pentaho/wcag , Please review, for toolbars that are used in PIR as well as PDD.
Used in https://github.com/pentaho/pentaho-platform-plugin-dashboards/pull/570

### CODE REVIEW

**Comment by buildguy** [comment]
### :x: Build failed in 1m 28s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 40s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :x: Build failed in 1m 41s
Build command:
```console
mvn clean verify -B -e -Daudit -amd -pl gwt/impl
```
---
 :exclamation: No tests found!
 ---
### Errors:
<details><summary><b>Filtered log</b> (click to expand)</summary>
<p>

```
script returned exit code 1
```
 
</p>
</details>
 
 

:information_source:  _This is an automatic message_

**Comment by AAravind27** [comment]
Closing this PR as the buttons where changed to ToolbarToggleButton, instead of ToolbarButton, that makes use of `setSelected( boolean selected )`

**Pull request closed without merging**
