### PR TITLE
[PDI-14531] - Not able to delete a folder created under the Home fold…

### PR DESCRIPTION
**Pull request by YuryBY**
@pentaho-nbaker, @rmansoor would you mind of reviewing/merging?
Unit tests don't provided since fix concerning only UI and tests creating seems unreasonably expensive here.

### CODE REVIEW

**Comment by YuryBY** [comment]
@pentaho-nbaker, @rmansoor,  any updates?

**Comment by pamval** [comment]
@rmansoor please take a look.

**Comment by pentaho-nbaker** [comment]
This may get us passed the immediate problem, but I don't like this fix in general. The issue I have with it is that by parenting the dialog to a new Shell, we run the risk that the user can accidentally focus the Repository Explorer and "lose" the confirmation dialog behind it. In essence on Linux the dialog becomes non-modal.

-Nick

**Comment by pentaho-nbaker** [comment]
Notice I'm not closing it. I'm "okay" with this going in for the immediate SP. However, I would like someone to dig into why the getParentObject() is not returning the proper Shell so we can get a "better" fix for the next release.

**Comment by rmansoor** [comment]
@pamval this is a change to the swt confirm box. Before I process this pull request, we need to test different place where this confirm box is being use to make sure it will not cause issue else where. I tested this issue in windows and windows is working properly. The only issue is on linux

**Comment by pamval** [comment]
@YuryBY please take into account Nick Baker's comments and investigate why the getParentObject() is not returning the proper Shell.
I'll add Nick's comments on the jira case. Closing the pull request for now.

**Pull request closed without merging**
